### ISSUE TITLE
Stable rust and `seq!` as expressions

### ISSUE THREAD

**Issue by WaffleLapkin** [dtolnay/seq-macro#1]
I'm wondering if it's possible to implement analogue to `seq!` which could
1. work on stable
2. work in expression position

So, e.g. this code would work:
```rust
let tuple = seq!(N in 0..=2 {
    (#(
        N, 
    )*)
});
assert_eq!(tuple, (0, 1, 2));
```
(My actual problem that I'm trying to implement trait on array types which need to access all elements and it's painful without `seq!`)

**Comment by dtolnay** [comment]
Yep yep -- https://github.com/dtolnay/proc-macro-workshop#function-like-macro-seq walks through how to implement that. A few different people have implementations, I don't know if any are on crates.io though.

https://www.youtube.com/watch?v=KVWHT1TAirU shows one implementation.
