### ISSUE TITLE
Infix pasting

### ISSUE THREAD

**Issue by bradleyharden** [dtolnay/seq-macro#14]
I don't think this is actually a solvable issue, but I just wanted to confirm that I'm not missing something.

I want to create a series of sequential identifiers with both a prefix and a suffix, e.g. `PrefixNSuffix`. As far as I can tell, I can't do this using `seq!` alone; I also need to use `paste!`. Is that correct?

I'm using something like

```rust
seq!(N in 0..11 {
    paste! {
        pub enum [<Prefix N Suffix>] {};
    }
});
```

In general, I find that I combine `seq!` and `paste!` quite frequently. Is there perhaps some convenient way to combine them? Or would you prefer to keep the functionality distinct?

**Comment by dtolnay** [comment]
Yeah `paste` is good for this. I don't feel inclined to reimplement either macro inside the other.
