### ISSUE TITLE
infix not only as suffix but also as prefix or in between

### ISSUE THREAD

**Issue by JHenneberg** [dtolnay/seq-macro#15]
It would be convenient to extend this crate that the infix can be not only used as suffix but also as a prefix or in between.

```rust
use seq_macro::seq;

seq!(P in 'b'..='d' {
    // expands to let 'line_point_a_to_point_a, ..., let line_point_d_to_point_a'
    let line_point_~P_to_point_a: Line;
});
```

Edit: Ok I just read #14 . I guess thats the way to work around it but I still have some trouble:

```rust
seq!(P in 'b'..='d' {
  paste! {
    // expands to let 'line_point_a_to_point_a, ..., let line_point_d_to_point_a'
    let [<line_point_ P _to_point_a>]: Line; // unsupported literal 
  }

});
```

**Comment by dtolnay** [comment]
The code in your second code block should work as of seq-macro 0.3.0 and paste 1.0.7.
