### ISSUE TITLE
Dynamic method chaining with seq/paste?

### ISSUE THREAD

**Issue by ristillu** [dtolnay/seq-macro#17]
I am using sqlx and a connection to a MS-SQL database. That particular configuration, due to limitations of SQL Server, means that if I have a container of things I want to bind against the query there is no way to auto-expand. A basic contrived example of what I'm doing looks like this:
```rs
#[derive(FromRow)] struct Id { id: i64 }
let values = vec![42, 34, 1, 78, 9, 1234, 98, 73, 39, 91];
let results = sqlx::query_as::<_, Id>(
    "SELECT id FROM some_table
    WHERE some_value in (@P1, @P2, @P3, @P4, @P5, @P6, @P7, @P8, @P9, @P10)"
    ).bind(values[0])
    .bind(values[1])
    .bind(values[2])
    .bind(values[3])
    .bind(values[4])
    .bind(values[5])
    .bind(values[6])
    .bind(values[7])
    .bind(values[8])
    .bind(values[9])
    .fetch_all(&pool).await?;
```
In real code I'd like to build up this query invocation dynamically. The parameters part I can dynamically create, that is everything within the string is fine (although if there's a solution to my problem using `seq` I'm open to using it for the query parameters part too).
In essence I would like to be able to (but can't work it out despite a few approaches I've tried) something like the following pseudocode:
```rs
#[derive(FromRow)] struct Id { id: i64 }
// values == some slice of let's say 1000
seq!(N in 0..1000i64 {
    let results = sqlx::query_as::<_, Id>("SELECT /* ... */")
        #( 
            .bind(values[ N])
        )*
        .fetch_all(&pool).await?;
})
```

There is a method to kind of do what I want by turning the values into a string of CSV and then using a SQL Server hack like `SELECT /* .. */ WHERE some_value IN (SELECT CONVERT(BIGINT, value) FROM string_split(@P1), ','))` but the upper limit is less than 100 i64s and I'm dealing with many thousands of values so it involves too much roundtripping and too many small queries so I'm curious if there's a better way with some `seq` magic.

**Comment by dtolnay** [comment]
Vector indices in Rust are of type usize, not i64.

```diff
- seq!(N in 0..1000i64 {
+ seq!(N in 0..1000usize {
```

Alternatively you could keep i64 in the loop and only cast to usize where the index is used.

```diff
-             .bind(values[N])
+             .bind(values[N as usize])
```
