### ISSUE TITLE
Const generics in seq! range

### ISSUE THREAD

**Issue by leighmcculloch** [dtolnay/seq-macro#19]
It'd be helpful if const generics could be used in the seq! range, but I suspect it isn't possible.

For example, it would help with situations like this in array initialization.

```rust
impl<T, const N: usize> TryFrom<MyType> for [T; N]
{
    type Error = ...;

    fn try_from(mt: MyType) -> Result<Self, Self::Error> {
        Ok([seq! { I in 0u32..=N
            mt.get(I)?,
        }])
    }
}
```

**Comment by dtolnay** [comment]
Const evaluation occurs only after macro expansion, so this isn't the crate you are looking for in that situation.
