### ISSUE TITLE
Nested seq!'s?

### ISSUE THREAD

**Issue by jullanggit** [dtolnay/seq-macro#25]
Is it possible to have nested seq!'s?  Heres the piece of code i couldn't get to work (context: I'm trying to transpose + simd-ise a `Vec<Vec<Card>>` for a little poker bot I'm making): 
```
    seq!(card_layer in 0..7 {
        let simd_cards = [
            #(
                seq!(lane in 0..32 {
                    u8x32::from_array([
                        #(
                            input_cardss[lane][card_layer].inner,
                        )*
                    ]),
                })
            )*
        ];
    });
```
And heres the error it produces: `expected one of `,`, `.`, `;`, `?`, `]`, or an operator, found seq`

**Comment by jullanggit** [comment]
Update: I got the code to work with array_macro's array!, but I'm leaving this issue open, as it might still be interesting for other people. Nonetheless, thanks for making the seq macro and have a great day!
```
let simd_cards: [Simd<u8, SIMD_LANES>; 7] =
    array![x => array![y => input_cardss[y][x].inner; SIMD_LANES].into();7];
```

**Comment by dtolnay** [comment]
Your comma was misplaced.

```diff
                             input_cardss[lane][card_layer].inner,
                         )*
-                    ]),
-                })
+                    ])
+                }),
```
