### ISSUE TITLE
Constants in seq! range

### ISSUE THREAD

**Issue by Visic** [dtolnay/seq-macro#3]
I'm not sure if it is possible, but it would be nice to be able to use constants in the range of a seq! macro.

e.g.

const LIMIT: usize = 10;
seq_macro::seq!(N in 0..LIMIT {{ ... }})

**Comment by dtolnay** [comment]
You can do this but the source of truth for the number needs to be a macro not a const:

```rust
use seq_macro::seq;

macro_rules! getlimit {
    ($expand:path) => {
        $expand!(10) // source of truth
    };
}

fn main() {
    macro_rules! expand {
        ($limit:literal) => {
            seq!(N in 0..$limit {
                println!(stringify!(N));
            });
        }
    }
    getlimit!(expand);
}
```

**Comment by Visic** [comment]
Thank you for the suggestion, however, I need to use this constant in several places, only one of which is the seq! macro.
I tried wrapping the constant in a macro I call instead, but unfortunately, I still get "error: expected integer" when I try to use it in the seq macro.

```
macro_rules! getlimit {
   () => {
        10
    };
}
```

**Comment by dtolnay** [comment]
The other places need to get it the same way with the getlimit macro I showed. For example:

```rust
macro_rules! id {
    ($limit:literal) => {
        $limit
    };
}

pub const LIMIT: usize = getlimit!(id);
```

**Comment by Visic** [comment]
It never occurred to me to use the macro to initialize the constant, very cool trick! I'm sure this is something I can work with.

I am happy to close this issue as it is functionally solved, and I thoroughly appreciate your help! However, it really is too bad we can't just use the constant. This approach seems pretty intricate for what I expected to be very simple.

**Comment by dtolnay** [comment]
> This approach seems pretty intricate for what I expected to be very simple.

Name resolution happens after macro expansion in rustc, so in order for anything to affect macro expansion (like how many times the body of seq is copied) it cannot rely on name resolution. Determining the value of a constant by name is an example of something that requires name resolution.

**Comment by SuperFluffy** [comment]
I have stumbled over this issue and tried the code example. It seems as of Rust 1.54 the compiler is unhappy about macros exanded within macros. Relevant playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2f19aaa1339742ae94f180d0b813d513

Code example:

```rust
macro_rules! id {
    ($limit:literal) => {
        $limit
    };
}

macro_rules! getlimit {
    ($expand:path) => {
        $expand!(10) // source of truth
    };
}

pub const LIMIT: usize = getlimit!(crate::id);
```

Produced error:

```
Compiling playground v0.0.1 (/playground)
error: macro expansion ignores token `!` and any following
  --> src/lib.rs:9:16
   |
9  |         $expand!(10) // source of truth
   |                ^
...
13 | pub const LIMIT: usize = getlimit!(crate::id);
   |                          -------------------- caused by the macro expansion here
   |
   = note: the usage of `getlimit!` is likely invalid in expression context

error[E0425]: cannot find value `id` in the crate root
  --> src/lib.rs:13:43
   |
13 | pub const LIMIT: usize = getlimit!(crate::id);
   |                                           ^^ not found in the crate root
   |
help: consider importing this function
   |
1  | use std::process::id;
   |

warning: unused macro definition
 --> src/lib.rs:1:1
  |
1 | / macro_rules! id {
2 | |     ($limit:literal) => {
3 | |         $limit
4 | |     };
5 | | }
  | |_^
  |
  = note: `#[warn(unused_macros)]` on by default

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground`
```

**Comment by SuperFluffy** [comment]
User Giuschi on discord provided the fix: the expansion needs to happen inside double curly braces:

```rust
macro_rules! getlimit {
    ($expand:path) => {{ // Note the braces!
        $expand!(10) // source of truth
    }};
}

macro_rules! id {
    ($limit:literal) => {
        $limit
    };
}

pub const LIMIT: usize = getlimit!(id);
```

**Comment by SuperFluffy** [comment]
The above code block breaks when passing in a macro containing `seq!`. With further help from discord, I ended up with the following.

```rust
use seq_macro::seq;

macro_rules! id {
    ($limit:literal) => {
        $limit
    };
}

macro_rules! getlimit {
    ($($expand:ident)::*) => {
        $($expand)::* !(8)
    };
}

const MAX: usize = getlimit!(id);

fn main() {
    macro_rules! expand {
        ($limit:literal) => {
            seq!(N in 0..$limit {
                println!(stringify!(N));
            });
        }
    }

    getlimit!(expand);
}
```
